version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
